#!/bin/bash

# Parse arguments.
while getopts 'hp:s:' argument
do
  case $argument in
    h)
      echo "usage: $0 [options] <additional files>"
      echo 'Commit changes in the PKGBUILD to an AUR distribution branch.'
      echo ' -h              show this help text'
      echo ' -p <script>     file to use in place of PKGBUILD'
      echo ' -s <separator>  separator between real file name and path in repository'
      exit ;;
    p) pkgbuild="$OPTARG" ;;
    s) separator="$OPTARG" ;;
    \?) exit 1 ;;
  esac
done
shift $(($OPTIND - 1))

# Generate missing .SRCINFO.
if ! [[ " ${@##*${separator:-:}} " =~ " .SRCINFO " ]]
then
  mksrcinfo ${pkgbuild:+"$pkgbuild"}
fi

# Determine branch name.
branch=aur
if [ -n "$(git rev-parse --show-prefix)" ]
then
  branch+="/$(grep -Po "(?<=pkgbase = ).*" .SRCINFO)"
fi

# Update the branch.
exec offbranch \
  -b "$branch" \
  ${separator+-s} ${separator+"$separator"} \
  "${pkgbuild:-PKGBUILD}${separator:-:}PKGBUILD" .SRCINFO "$@"
