#!/bin/bash

# Parse arguments.
while getopts 'hc' argument
do
  case $argument in
    h)
      echo "usage: $0 [options] <package>"
      echo 'Set up git remote and branch pointing to AUR package repository.'
      echo ' -h  show this help text'
      echo ' -c  include the name of the package in branch and remote name'
      exit ;;
    c) name=/ ;;
    \?) exit 1 ;;
  esac
done

readonly package="${!OPTIND}"
if [ -z "$package" ]
then
  gettext -sd bash 'argument expected'
  exit 1
fi

# Prepare branch.
exec offremote \
  -n "aur${name+/${package}}" \
  "ssh://aur@aur4.archlinux.org/${package}.git"
