#!/bin/bash

search='^[[:space:]]*# (vim|template\ (start.*name=([[:alnum:]-]*)|end)).*$'
skip() {
  continue
}

while getopts 'hm' argument
do
  case $argument in
    h)
      echo "usage: $0 [options] < PKGBUILD"
      echo 'cleans a given PKGBUILD'
      echo ' -h  show this help text'
      echo ' -m  only remove duplicates'
      exit ;;
    m)
      search='^[[:space:]]*# (template\ (start.*name=([[:alnum:]-]*))).*$'
      skip() {
        :
      } ;;
    \?) exit 1 ;;
  esac
done


IFS=''

collect_until_end() {
  while read -r line
  do
    if [[ $line =~ ^[[:space:]]*'# template '(start|end)';'.*$ ]]
    then
      case ${BASH_REMATCH[1]} in
        start)
          collect_until_end ;;
        end)
          return 0 ;;
      esac
    fi
  done
  return 1
}

seen=/

while read -r line
do
  if ${empty-false}
  then
    empty=false
    if [ "$line" = '' ]
    then
      continue
    fi
  fi
  if [[ $line =~ $search ]]
  then
    case ${BASH_REMATCH[1]} in
      vim) unset last ;;
      template\ start*)
        name=${BASH_REMATCH[3]}
        if [[ $name =~ ^($seen)$ ]]
        then
          collect_until_end || exit 1
          empty=true
          continue
        else
          seen+="|${name}"
        fi ;;
    esac
    skip
  fi
  echo -En "$last"
  last=$line$'\n'
done < ${!OPTIND:-/dev/stdin}
echo -En "$last"
