#!/bin/bash

IFS=''

collect_until_end() {
  while read -r line
  do
    if [[ $line =~ ^[[:space:]]*'# template '(start|end)';'.*$ ]]
    then
      case ${BASH_REMATCH[1]} in
        start)
          collect_until_end ;;
        end)
          return 0 ;;
      esac
    fi
  done
  return 1
}

seen=/

while read -r line
do
  if [[ $line =~ ^[[:space:]]*'# '(vim|template\ (start.*name=([[:alnum:]-]*)|end)).*$ ]]
  then
    case ${BASH_REMATCH[1]} in
      vim) unset last ;;
      template\ start*)
        name=${BASH_REMATCH[3]}
        if [[ $name =~ ^($seen)$ ]]
        then
          collect_until_end || exit 1
        else
          seen+="|${name}"
        fi ;;
    esac
  else
    echo -En "$last"
    last=$line$'\n'
  fi
done
echo -En "$last"
