#!/bin/bash

# check arguments
if [ $# -ne 2 ]
then
  echo "usage: $0 <source> <destination>"
  echo 'Copies the value of the pkgver variable from one PKGBUILD to another.'
fi

srcver=$(grep -Po '(?<=^pkgver=)[^ ]*' "$1")
dstver=$(grep -Po '(?<=^pkgver=)[^ ]*' "$2")
if [ $srcver != $dstver ]
then
  if [ -w "$2" ]
  then
    sed --follow-symlinks -i "s:^pkgver=[^ ]*:pkgver=$srcver:;s:^pkgrel=[^ ]*:pkgrel=1:" "$2"
  else
    printf "$0: $(gettext -d 'pacman-scripts' \
      "%s is not writeable -- pkgver will not be updated")\n" "$2"
    exit 2
  fi
fi
