#!/bin/bash

IFS=''

collect_until_end() {
  while read -r line
  do
    if [[ $line =~ ^[[:space:]]*'# template '(start|end)';'.*$ ]]
    then
      case ${BASH_REMATCH[1]} in
        start)
          collect_until_end ;;
        end)
          return 0 ;;
      esac
    fi
  done
  return 1
}

seen=/

while read -r line
do
  if [[ $line =~ ^[[:space:]]*'# template start'.*name=([[:alnum:]-]*).*$ ]]
  then
    name=${BASH_REMATCH[1]}
    if [[ $name =~ ^($seen)$ ]]
    then
      collect_until_end || exit 1
      continue
    else
      seen+="|${name}"
    fi
  fi
  echo -E "$line"
done
