# Maintainer: Dominik Fischer <d dot f dot fischer at web dot de>
pkgname=makepkg-expanded-git
pkgver=r0
pkgrel=1
# Do not try to track version changes with git. The version generated by the pkgver
# function in the git template will in turn reference the commit hash, so commiting
# a version change will change the version, which is an unbreakable race condition.
pkgdesc="builds packages and aurballs expanding templates off-file"
arch=('any')
url="https://github.com/dffischer/makepkg-expanded"
license=('GPL')
depends=('pacman')
makedepends=('ruby-ronn')

# template input; name=git

build() {
  cd $_gitname
  ronn --roff makepkg-expanded.md clean-template.md
}

package() {
  cd $_gitname
  install -Dt "$pkgdir/usr/bin" makepkg-expanded clean-template cp-pkgver
  install -Dm644 -t "$pkgdir/usr/share/man/man1" makepkg-expanded.1 clean-template.1
}
